version: '3.3'
services:
    dp-import-cantabular-dataset:
        build:
            context: ../..
            dockerfile: Dockerfile.local
        command:
        - go 
        - test 
        - -cover 
        - -coverpkg=github.com/ONSdigital/dp-import-cantabular-dataset/... 
        - -component
        volumes:
            - ../..:/dp-import-cantabular-dataset
        depends_on:
            - kafka
            - zookeeper
        ports:
            - "26100:26100"
        environment:
            BIND_ADDR:                          ":26300"
            SERVICE_AUTH_TOKEN:                 "testToken"
            COMPONENT_TEST_USE_LOG_FILE:        "${COMPONENT_TEST_USE_LOG_FILE-false}"
            CANTABULAR_HEALTHCHECK_ENABLED:     "true"
            STOP_CONSUMING_ON_UNHEALTHY:        "true"
            KAFKA_ADDR:                         "kafka:9092"
            KAFKA_CONSUMER_MIN_BROKERS_HEALTHY: 1
            KAFKA_PRODUCER_MIN_BROKERS_HEALTHY: 1
            KAFKA_SEC_PROTO:                    ""
