---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.18.3

inputs:
  - name: dp-import-cantabular-dataset

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-import-cantabular-dataset/ci/scripts/build.sh
